# Generated by Django 6.0.5 on 2026-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.FileField(blank=True, upload_to='organization_images/'),
        ),
    ]
